### ISSUE TITLE
Issue when running some scipy.sparse.linalg code inside Pyodide venv

### ISSUE THREAD

**Issue by lesteve** [pyodide/pyodide#3865]
## 🐛 Bug

Running Scipy code inside a Pyodide venv yields to somme `Error: Dynamic linking error: cannot resolve symbol s_cmp`. Running inside a browser works fine and I am pretty sure running a .js with node explicitly does work as well since I have been doing it for a while in https://github.com/lesteve/scipy-tests-pyodide. Maybe the issue is with the Pyodide venv python nodejs wrapper?

### To Reproduce

```
pyodide venv .pyodide-venv
source .pyodide-venv/bin/activate
pip install scipy
python test.py
```

Where `test.py` has the following content:
```py
import numpy as np

from scipy.sparse.linalg import svds

rng = np.random.default_rng(0)
A = rng.random((10, 10))

res = svds(A, k=3, which='LM', random_state=0)
```

```
Stack (most recent call first):
  File "/home/lesteve/test/.pyodide-venv/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/arpack/arpack.py", line 537 in iterate
  File "/home/lesteve/test/.pyodide-venv/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/arpack/arpack.py", line 1700 in eigsh
  File "/home/lesteve/test/.pyodide-venv/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/_svds.py", line 525 in svds
  File "/home/lesteve/test/test.py", line 8 in <module>
Error: Dynamic linking error: cannot resolve symbol s_cmp
    at stubs.<computed> (/home/lesteve/test/.pyodide-xbuildenv-0.26.0/0.26.0/xbuildenv/pyodide-root/dist/pyodide.asm.js:10:148862)
    at wasm://wasm/000fb3c2:wasm-function[207]:0x173c0
    at wasm://wasm/000fb3c2:wasm-function[180]:0x4472
    at wasm://wasm/0003e6d6:wasm-function[107]:0xbfa0
    at _PyEM_TrampolineCall_JS (/home/lesteve/test/.pyodide-xbuildenv-0.26.0/0.26.0/xbuildenv/pyodide-root/dist/pyodide.asm.js:10:125866)
    at wasm://wasm/0267d6e2:wasm-function[1134]:0x1c2db7
    at wasm://wasm/0267d6e2:wasm-function[1143]:0x1c35c8
    at wasm://wasm/0267d6e2:wasm-function[3408]:0x2a05c2
    at wasm://wasm/0267d6e2:wasm-function[3406]:0x2960a0
    at wasm://wasm/0267d6e2:wasm-function[4211]:0x30a9c5
```

Edit: for compleness as I was mentioning, the same code run with node directly `node test.js` does work:

```js
const { opendir } = require('node:fs/promises');
const { loadPyodide } = require("pyodide");

async function main() {
  let pyodide = await loadPyodide();
  
  await pyodide.loadPackage(["scipy"]);
  await pyodide.runPythonAsync(`
  import numpy as np
  
  from scipy.sparse.linalg import svds
  
  rng = np.random.default_rng(0)
  A = rng.random((10, 10))
  
  res = svds(A, k=3, which='LM', random_state=0)
  `);

}

main();
```

### Expected behavior

No error

### Environment

- Pyodide Version: 0.26.0

**Comment by hoodmane** [comment]
The problem is that the .so preloading logic is different in the Pyodide virtual environment. Instead of using `dynload.ts`:
https://github.com/pyodide/pyodide/blob/main/src/js/dynload.ts
it uses this much crappier custom implementation:
https://github.com/pyodide/pyodide/blob/main/src/templates/python#L125-L145
It would be nice to understand more specifically what is going wrong though. This is important for my hopes of using JS promise integration to avoid the preloading step.

**Comment by lesteve** [comment]
I debugged a bit further and the undefined symbol is `s_cmp` that comes from clapack_all.so (true for 
the latest release, in `main` it comes from libopenblas.so)

My summary:
- `clapack_all.so` is not loaded since it is not in `lib/python3.11/site-packages` but in `lib`. This is probably the case that other libraries in `lib` are not loaded either
- using `loadDynlink` on clapack_all.so only seems to fix the issue with `global=true`.

I had a look at https://github.com/pyodide/pyodide/blob/main/src/js/dynload.ts but I don't really understand the logic well enough to know what is a good way forward, in particular I am not sure about what `global` is used for. It seems like the order of library loading is important too (global should first according to some comments).

**Comment by ryanking13** [comment]
I think `clapack_all.so` is loaded but it is not loaded with `global: true` so the symbol is not resolved. Probably we need to load libraries in `DSO_DIR` with `global: true` before loading libraries that are in site-packages.

It is worth noting that this is a bug in Emscripten (https://github.com/emscripten-core/emscripten/issues/18264)... it would be great if we can fix this upstream instead of using `global` hack.

**Comment by lesteve** [comment]
Thanks for your comment, AFAICT from the code below, only shared libraries inside site-packages are loaded. `clapack_all.so` is not in site-packages but in `lib` and it is not loaded but maybe I am missing something:

https://github.com/pyodide/pyodide/blob/main/src/templates/python?rgh-link-date=2023-05-17T18%3A24%3A56Z#L125-L145

I'll try to have a closer look at one point, although I would say this is definitely not at the top of my priorities right now ...

**Comment by ryanking13** [comment]
[`loadDynlib`](https://github.com/pyodide/pyodide/blob/f8c6b8ade60f5d349c1c8b8487c772b4893759f6/src/js/dynload.ts#L96) loads dependencies too, so if shared libraries of scipy are linked with `clapack_all.so` then it will be loaded. So I think you can try setting `global` argument to true here: 

https://github.com/pyodide/pyodide/blob/f8c6b8ade60f5d349c1c8b8487c772b4893759f6/src/templates/python#L140

**Comment by lesteve** [comment]
When using `py._module.API.loadDynlib(dynlib, true)` it goes a little bit further (the symbol is defined) but fails with a `null function or function signature mismatch error`. I checked with a debugger indeed the function is null (i.e. the last value on the stack as shown in debugging docs is 0).

I tried manually changing the code to load `clapack_all.so` before loading the site-packages `.so` files and it seems to fix the issue.

I have to admit, I don't know how to fix the problem in a generic and non-hacky way though.

**Comment by rgommers** [comment]
It looks like we ran into this same issue with the `s_cmp` symbol missing (with code that also uses `scipy.linalg`) when testing scikit-image out of tree (https://github.com/scikit-image/scikit-image/pull/7265#issuecomment-1971713011). 

> It is worth noting that this is a bug in Emscripten ([emscripten-core/emscripten#18264](https://github.com/emscripten-core/emscripten/issues/18264))... it would be great if we can fix this upstream instead of using `global` hack.

That issue is now closed, and it says that the fix was released in Emscripten 3.1.34. The current version used in Pyodide is higher (3.1.46 in the scikit-image build). So that may not have been the full story.

@lesteve is this why you are using [pytest-pyodide.js](https://github.com/scikit-learn/scikit-learn/blob/main/build_tools/azure/pytest-pyodide.js) in scikit-learn CI rather than a venv?

**Comment by ryanking13** [comment]
> That issue is now closed, and it says that the fix was released in Emscripten 3.1.34. The current version used in Pyodide is higher (3.1.46 in the scikit-image build). So that may not have been the full story.

Yes, that issue is resolved in Emscripten 3.1.34, but, when I tried to remove the global hack from Pyodide in the past, I still faced the same problem. I haven't had a chance to analyze this in detail since then, so I don't know the exact reason, but there still seems to be an issue with symbol visibility.

**Comment by lesteve** [comment]
> @lesteve is this why you are using [pytest-pyodide.js](https://github.com/scikit-learn/scikit-learn/blob/main/build_tools/azure/pytest-pyodide.js?rgh-link-date=2024-03-01T10%3A17%3A32Z) in scikit-learn CI rather than a venv?

Yes exactly! IMO the additional js script is not too hard to write, I do have a few variations of this script in other places for example https://github.com/lesteve/scipy-tests-pyodide/blob/main/scipy-pytest.js. It also feels slightly less magical than the Pyodide venv where `python` is actually a nodejs script.

**Comment by lesteve** [comment]
I tried again with Pyodide 0.25.1 and 0.26.0 and I can not reproduce this issue anymore locally :thinking: :tada: :thinking:.

@agriyakhetarpal maybe you can double-check that you don't need the js wrapper script any more in https://github.com/scikit-image/scikit-image/pull/7350? I can certainly try in the scikit-learn CI as well.

Context: I was pinged by @hoodmane in https://github.com/scikit-hep/boost-histogram/pull/938#issuecomment-2143276717 which motivated to look at this again.

**Comment by lesteve** [comment]
Actually my bad, I still get an error locally which is the same as in scikit-image `Error: Dynamic linking error: cannot resolve symbol s_cmp` https://github.com/scikit-image/scikit-image/pull/7350#issuecomment-2003872551
```
  File "/home/lesteve/test/.pyodide-venv/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/arpack/arpack.py", line 537 in iterate
  File "/home/lesteve/test/.pyodide-venv/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/arpack/arpack.py", line 1700 in eigsh
  File "/home/lesteve/test/.pyodide-venv/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/_svds.py", line 525 in svds
  File "/home/lesteve/test/test.py", line 8 in <module>
Error: Dynamic linking error: cannot resolve symbol s_cmp
    at stubs.<computed> (/home/lesteve/test/.pyodide-xbuildenv-0.26.0/0.26.0/xbuildenv/pyodide-root/dist/pyodide.asm.js:10:148862)
    at wasm://wasm/000fb3c2:wasm-function[207]:0x173c0
    at wasm://wasm/000fb3c2:wasm-function[180]:0x4472
    at wasm://wasm/0003e6d6:wasm-function[107]:0xbfa0
    at _PyEM_TrampolineCall_JS (/home/lesteve/test/.pyodide-xbuildenv-0.26.0/0.26.0/xbuildenv/pyodide-root/dist/pyodide.asm.js:10:125866)
    at wasm://wasm/0267d6e2:wasm-function[1134]:0x1c2db7
    at wasm://wasm/0267d6e2:wasm-function[1143]:0x1c35c8
    at wasm://wasm/0267d6e2:wasm-function[3408]:0x2a05c2
    at wasm://wasm/0267d6e2:wasm-function[3406]:0x2960a0
    at wasm://wasm/0267d6e2:wasm-function[4211]:0x30a9c5
 ```

I reproduce the same issue in scikit-learn CI: https://github.com/scikit-learn/scikit-learn/pull/29156#issuecomment-2143715264

I'll edit the original post to reflect this.

**Comment by hoodmane** [comment]
With the node runner:
```js
> resolveGlobalSymbol("s_cmp")
< {sym: undefined, name: 's_cmp'}

> LDSO.loadedLibsByName["libopenblas.so"].exports.s_cmp
< ƒ $s_cmp() { [native code] }
```
vs in normal Pyodide:
```js
> resolveGlobalSymbol("s_cmp")
< {name: 's_cmp', sym: ƒ}

> LDSO.loadedLibsByName["libopenblas.so"].exports.s_cmp
< ƒ $s_cmp() { [native code] }
```

**Comment by hoodmane** [comment]
@ryanking13 can we decide whether `forceGlobal` should be true based on whether the dynamic library is not installed in `site-packages`? So that it's loaded globally if it's in `neededDylibs` or if it's in `/usr/lib/`? This would let us remove the usage of the `InternalPackageData` from `loadDynlibsFromPackage` and then I could relatively easily reuse it in the cli runner.

**Comment by hoodmane** [comment]
I'm actually not sure why `libopenblas.so` is loaded at all since the code makes it look like we only load libs under `site-packages` and it's installed at `.venv-pyodide/lib/libopenblas.so`...

**Comment by hoodmane** [comment]
Ah right it's because `defaultLdLibraryPath` includes `.venv-pyodide/lib/`

**Comment by hoodmane** [comment]
I think what we need is this patch to Emscripten. This should also allow us to strip a lot of the stuff out of `dynload.ts`.
```patch
--- a/src/library_dylink.js
+++ b/src/library_dylink.js
@@ -889,11 +889,15 @@ var LibraryDylink = {
 
     // now load needed libraries and the module itself.
     if (flags.loadAsync) {
+      const origGlobal = flags.global;
+      flags.global = true;
       return metadata.neededDynlibs
         .reduce((chain, dynNeeded) => chain.then(() =>
           loadDynamicLibrary(dynNeeded, flags)
         ), Promise.resolve())
-        .then(loadModule);
+        .then(() => {
+          flags.global = origGlobal;
+        }).then(loadModule);
     }
 
     metadata.neededDynlibs.forEach((needed) => loadDynamicLibrary(needed, flags, localScope));
```

**Comment by ryanking13** [comment]
> can we decide whether forceGlobal should be true based on whether the dynamic library is not installed in site-packages? So that it's loaded globally if it's in neededDylibs or if it's in /usr/lib/? This would let us remove the usage of the InternalPackageData from loadDynlibsFromPackage and then I could relatively easily reuse it in the cli runner.

For now, yes, but I don't think it is a correct direction. Ideally, those libraries should work even if they are not loaded globally, which is how things behave in linux environment.

Originally, I force-loaded those libraries in "global" mode because emscripten had a bug that local symbols were not visible (https://github.com/emscripten-core/emscripten/issues/18264). Emscripten people fixed that bug, but when the last time I checked, it wasn't working well in Pyodide...

**Comment by ryanking13** [comment]
Seems like this (https://github.com/emscripten-core/emscripten/pull/21985) was related to this issue. I'll take a look soon.

**Comment by hoodmane** [comment]
> Ideally, those libraries should work even if they are not loaded globally, which is how things behave in linux environment.

It seems like you have to remind me about this roughly once a year =)
