### ISSUE TITLE
Stderr is missing when python code has syntax or runtime error

### ISSUE THREAD

**Issue by bddicken** [pyodide/pyodide#3938]
## 🐛 Bug

When using the `runPython` method of Pyodide to evaluate a chunk of python code stored in a strong, the python-produced stderr is unavailable to view if the code contains a problem that would generate a syntax or runtime error. In "regular" Python, when an error is produced PYthon spits out the error message to stderr. However, I cannot seem to capture these error messages using the procedure for capturing stderr in the Pyodide documentation The program below illustrates this.

### To Reproduce

```html
<!doctype html>                       
<html>       
  <head>                              
      <script src="https://cdn.jsdelivr.net/pyodide/v0.23.3/full/pyodide.js"></script>
  </head>                             
  <body>                              
    <script type="text/javascript">   
      async function main(){          
             
        /*  Create variable store store the python-generated stdout and stderr */
        let runStdout = '';           
        let runStderr = '';           
                                      
        /* Load Pyodide, and give it callback functions so that I can store the outputs of stdout and stderr */
        let pyodide = await loadPyodide( {
          stdout: function (x) { runStdout += x; },
          stderr: function (x) { runStderr += x; }
        });                           
                                      
        /*                            
        Execute a small program with a simple NameError.
        Python *should* produce the following stderr when this program is run:
             
        Traceback (most recent call last):
          File "?.py", line 1, in <module>
            print(x)                  
        NameError: name 'x' is not defined
             
        */                            
        try {                         
          pyodide.runPython(`print(x)`);
        } catch {                     
          /* I just want to continue and see the python error message */
        }                             
                                      
        /* Stdout is empty, as expected*/
        console.log('STDOUT:\n' + runStdout);
        /* This print statement *should* print out the error message shown above, but it does not. */
        console.log('STDERR:\n' + runStderr);
      }      
             
      main();                                                                                                                                                   
    </script>                         
  </body>                             
</html>
```

### Expected behavior

I would think that I *should* be seeing something along the lones of this output in the browser console:

```
STDOUT:
STDERR:
Traceback (most recent call last):
  File "/Users/bddicken/Desktop/x.py", line 1, in <module>
    print(x)                      
NameError: name 'x' is not defined
```

However, Instead I get:

```
STDOUT:
STDERR:
Traceback (most recent call last):
  File "/Users/bddicken/Desktop/x.py", line 1, in <module>
    print(x)                      
NameError: name 'x' is not defined
```

I understand that a javascript error is thrown in this case, which in my example code I am catching and ignoring. However, I specifically want to see the error that the python interpreter produces, not the full JS error.

### Environment

- Pyodide Version: v0.23.3
- Browser version: Brave 1.52 and Chrome 114

### Additional context

I am new to Pyodide, so hopefully I am not missing something obvious. If there is some other way to overcome this problem, please let me know. Also, thank you for developing this library!

**Comment by hoodmane** [comment]
This works as intended. You can access the Python error object as `sys.last_value`. If you want that printed to `stderr`, you can use `pyodide.runPython(`import traceback; traceback.print_exception(sys.last_value)`);`. Or if you catch the js error and look at `err.message`, this contains the error text that Python would format. 

But if you could say in a bit more detail what you are trying to do, maybe we can provide other suggestions.

**Comment by bddicken** [comment]
Thank you @hoodmane for the speedy reply! It seems as if the `err.message` technique will get me almost to where I want, so that will probably suffice for my purpose. I'll just have to chop off some of the "extra" error output I'd put before.

Perhaps I should add a little context here. When running python normally on a unix system, we can do something like this in the shell:

```
$ echo "print(x)" > test.py
$ python3 test.py 2> stderr.txt
```
After this, we will see something like this in `stderr.txt`:

```
Traceback (most recent call last):
  File "....test.py", line 1, in <module>
    print(x)
NameError: name 'x' is not defined
```

It is typical behavior for python-generated error messages to be sent to the stderr stream of the process executing the Python code. Thus, it would make intuitive sense to be able to capture such output using Pyodide in the way that I did in my example code. However, in this case such an intuition failed me.

It seems like capturing error output accurately would be a important feature of a project like this, but at the moment it isn't well documented how to do so (for example, getting the value of `err.message` did not come up in my investigation).

**Comment by ryanking13** [comment]
I also think this is working as intended.

> It seems like capturing error output accurately would be a important feature of a project like this, but at the moment it isn't well documented how to do so (for example, getting the value of err.message did not come up in my investigation).

It is a regular [JavaScript Error object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error). If you are not familiar with JavaScript, you can also capture errors inside Python using a regular try-except statement.

But yeah, having a FAQ about how to handle errors would be nice. There's always more going on at Pyodide than core contributors can handle, so sadly improving documentation takes a back seat. So it would be great if you could contribute to the documentation on this.

**Comment by bddicken** [comment]
Thanks @ryanking13. I am not very familiar with the details of JS error object.

From my perspective, what's happening here is a blurring of lines between a Js error and a Python error. There is technically nothing "wrong" with the Js code in my example. I didn't try to refer to a variable that didn't exist in Js, I did so in Python. Thus, it seems odd that the way to access the error output of an error from Python is an exception being thrown and an error object in Js. This object seems to be representing two things at once - a Js "error" and also a true Python error. 

It might make more intuitive sense for users of this library to have the `pyodide.runPython` method (which is basically just an invocation of a python interpreter) to function as similarly as possible to how the standard python interpreter does, which is to spit these errors out to stdout. This change may make getting at error message more clear to future adopters of this library.

Of course, I'm not in the trenches of implementation, so you as the experts may disagree :).

As for as updating documentation, what is the procedure for that? Are the docs a part of this repo, or hosted elsewhere?

**Comment by bddicken** [comment]
Also, my bad. I just realized I made a blunder in my original post. Initially, I had indicated that the actual output I got printing from the example code included the python error. However, the reality is that it does not (I fixed the post). Hopefully you were able to figure this out, but I'm clarifying in case.

**Comment by ryanking13** [comment]
Conceptually and physically, Pyodide is more of a library than a process. It's not a process, so it doesn't terminate on error, and it doesn't have an exit code.

If you think of it as a library within a process (browser tab), it's a structure where a caller (JS) calls a callee (Python), so I think it's natural to throw an exception when an error occurs.

> It might make more intuitive sense for users of this library to have the pyodide.runPython method (which is basically just an invocation of a python interpreter) to function as similarly as possible to how the standard python interpreter does

I completely agree with this, and it's also the goal of Pyodide, but I think the most natural behaviour for handling errors is to tell that something went wrong, and that's what I think raising an exception does: it lets the caller know that something went wrong in the callee, so they can handle it.

**Comment by ryanking13** [comment]
> As for as updating documentation, what is the procedure for that? Are the docs a part of this repo, or hosted elsewhere?

You can read the documentation about [Error conversion here](https://pyodide.org/en/stable/usage/type-conversions.html#errors), and you can modify the [documentation code here](https://github.com/pyodide/pyodide/blob/main/docs/usage/type-conversions.md#errors). If you feel that the page isn't easy enough to find, or that it's too unfriendly, it might be a good idea to add a related topic to the [FAQ](https://github.com/pyodide/pyodide/blob/main/docs/usage/faq.md).

**Comment by WebReflection** [comment]
Hello there, I am struggling with this (imho) bug too and it's not clear to me at this point what `stderr` does, when, or if ever.

Please allow me to show a copy/paste whole example:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script type="module">
    import { loadPyodide } from 'https://cdn.jsdelivr.net/pyodide/v0.23.4/full/pyodide.mjs';

    const pyodide = await loadPyodide({
      // use warn instead to make it visible this works
      stdout: console.warn,
      // wrap it to show this never gets called
      stderr(...args) {
        console.info('WHEN IS IT EVER HAPPENING?');
        // no matter what I do here
        console.log(...args);
      }
    });

    pyodide.runPython(`
        from js import document
        from datetime import datetime as dt
        from pyodide.ffi.wrappers import add_event_listener

        element = document.querySelector("#just-a-button")

        def on_click(event):
            # this works as expected, it warns instead of logging
            print(f"Hello from Python! {dt.now()}")

            # no stderr here ... this is still Python code but I need to catch this
            shenanigans()

        add_event_listener(element, "click", on_click)

        # this works as expected, it warns instead of logging
        print(f"Hello from Python! {dt.now()}")

        # no stderr here ... this is Python code (commented out as irrelevant)
        # shenanigans()
    `);
  </script>
</head>
<body>
  <button id="just-a-button">click and check the console</button>
  <div id="result"></div>
</body>
</html>
```

The provided `stderr` is never reached and while I can do a `try/catch` around `runPython` and check JS or Python, or whatever error I have, it's impossible for me to check that the listener had an error.

I believe the `stderr` as it is is breaking a lot of expectations but most importantly with async code or listeners around is barely impossible to understand what to do or when *unless* something like this is used instead:

```html
  <script>
    addEventListener('error', ({message}) => {
      console.info('IS THIS THE WAY?');
      console.error(message);
    });
  </script>
```

That would catch the error from *at-distance* running code but it feels like `stderr` is completely useless then so at least it would be great to write in the documentation **when** the `stderr` is ever invoked, thank you!

**Comment by ryanking13** [comment]
My thoughts are still the same as the comment above (https://github.com/pyodide/pyodide/issues/3938#issuecomment-1598546005), I think it's more natural to throw an exception than to print an error to stderr.

However, if a lot of people find this counterintuitive, I think we could consider not only throwing an exception when Python encounters an error, but also outputting an error message to stderr. Probably we could consider adding an option to loadPyodide to turn it on/off.

**Comment by WebReflection** [comment]
@ryanking13

> think it's more natural to throw an exception than to print an error to stderr.

in my example nobody can catch that error outside pyodide internals though ... we can't wrap every branching async code or listener, we have **only** `stderr` to hook into errors and we might want to also redirect errors to a terminal / repl and it's mostly impossible to do so elegantly right now.

My question remains though: in which circumstance `stderr` is useful? I assume a print to stderr might be answer but if that's the only entry point, how is anyone supposed to catch errors without needing a listener in the global context? That listeners is hardly even related with *what* or *where* the error happened, so our hands are a bit tied here.

> Probably we could consider adding an option to loadPyodide to turn it on/off.

I think a new `stderr_errors: true` option/flag (or whatever name you prefer) would solve every issue and make expectations explicit, alternatively I think a `catch(error) {}` option, unrelated to `stderr` would work lovely too and maybe it reasons well with your expectations: if provided, errors will be passed along that callback instead of just throwing in the main/worker thread out of the box.

**Comment by WebReflection** [comment]
P.S. the main issue with `addEventListener('error')` is that it's really error prone:

  * any not caught error will pass through it, hard to make it robust for Python/Pyodide only gotchas
  * if there are multiple pyodide bootstrapped on the same realm / page, it's impossible to distinguish which of them caused the error

I hope this helps thinking about a better solution because right now we do have various possible issues with the current approach.

**Comment by hoodmane** [comment]
I think the solution for this is that if errors propagate out of Python we should call `sys.excepthook`. The reason I've never implemented this is that we have to count the number of times we entered Python code to only make the call when the error exits the outermost python. I added `PY_ENTER` and `PY_EXIT` macros that wrap every entry to/exit from Python so we just have to increment/decrement a counter and if it reaches zero as an error is raised call the excepthook. I should probably just do that...

**Comment by WebReflection** [comment]
@hoodmane in my example the callback happens on click but the code enters and exits with no issue ... to clarify at least my thoughts:

  * the Python program should not *exit*
  * errors can happen at distance (async / listeners) still confined in the Python world

If these two points are clear, I'd be happy to use the next version that actually allows us to understand if some Python code did throw an uncaught error at any point in time, allowing us to show this error on the DOM, as example, whenever that's desired.

**Comment by ryanking13** [comment]
> in my example nobody can catch that error outside pyodide internals though ... we can't wrap every branching async code or listener, we have only stderr to hook into errors and we might want to also redirect errors to a terminal / repl and it's mostly impossible to do so elegantly right now.

Hmm, yes, that's a fair point...

> I think the solution for this is that if errors propagate out of Python we should call sys.excepthook.

+1 for calling `sys.excepthook` when the error propagates out of Python.
