### ISSUE TITLE
Error loading TatSu package

### ISSUE THREAD

**Issue by pressureless** [pyodide/pyodide#740]
Hi,
I encounter an issue when trying to load [TatSu](https://tatsu.readthedocs.io/en/stable/) package which is a tool that takes grammars in a variation of EBNF as input, and outputs memoizing (Packrat) PEG parsers in Python.

The msg shows that micropip has installed TatSu 4.4.0 successfully, but even the simplest official [demo](https://tatsu.readthedocs.io/en/stable/mini-tutorial.html) can not be compiled. It's strange that according to the msg, the error remains in TatSu while the demo does work correctly on my system(Python3.7.4+TatSu4.4.0, same environment).

Here is the python code.
```
    pythonCode = `
def do_compile(*args): 
    from tatsu import parse
    from tatsu.util import asjson
    from tatsu._version import __version__
    import sys
    print("Python version")
    print (sys.version)
    print("Version info.")
    print (sys.version_info)
    print("version:", __version__)

    GRAMMAR = '''@@grammar::CALC


start
    =
    expression $
    ;


expression
    =
    | expression '+' ~ term
    | expression '-' ~ term
    | term
    ;


term
    =
    | term '*' ~ factor
    | term '/' ~ factor
    | factor
    ;


factor
    =
    | '(' ~ expression ')'
    | number
    ;


number
    =
    /\d+/
    ;'''
    ast = parse(GRAMMAR, '3 + 5 * ( 10 - 20 )')
    print("compile", ast)

import micropip
micropip.install('http://127.0.0.1:8000/TatSu-4.4.0-py2.py3-none-any.whl').then(do_compile) 

    `
```

Here is the error msg.
<img width="841" alt="image" src="https://user-images.githubusercontent.com/8511053/89971095-4f921e00-dc28-11ea-819c-f559dee11f6b.png">

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/8511053/89970576-1c9b5a80-dc27-11ea-94e9-23f29fbc9848.png">

Here is the correct output on local system.
<img width="639" alt="image" src="https://user-images.githubusercontent.com/8511053/89971717-0216b080-dc2a-11ea-9c58-5733c6ad79de.png">

**Comment by phorward** [comment]
Hi @pressureless,
thanks for your bug report. I gave it a try in the [Pyodide REPL](https://pyodide-cdn2.iodide.io/v0.15.0/full/console.html) using the official tatsu from PyPI and it works like a charm! I just entered your code in the console in a slightly modified way, here's the listing:
```
Welcome to the Pyodide terminal emulator 🐍
>>> import micropip
>>> micropip.install('tatsu')
Installed regex, tatsu
>>> import tatsu
>>> def do_compile(*args): 
    from tatsu import parse
    from tatsu.util import asjson
    from tatsu._version import __version__
    import sys
    print("Python version")
    print (sys.version)
    print("Version info.")
    print (sys.version_info)
    print("version:", __version__)

    GRAMMAR = '''@@grammar::CALC


start
    =
    expression $
    ;


expression
    =
    | expression '+' ~ term
    | expression '-' ~ term
    | term
    ;


term
    =
    | term '*' ~ factor
    | term '/' ~ factor
    | factor
    ;


factor
    =
    | '(' ~ expression ')'
    | number
    ;


number
    =
    /\d+/
    ;'''
    ast = parse(GRAMMAR, '3 + 5 * ( 10 - 20 )')
    print("compile", ast)
>>> do_compile()
Python version
3.7.4 (default, May 20 2020, 19:25:33) 
[Clang 6.0.1 ]
Version info.
sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
version: 5.5.0
compile ('3', '+', ('5', '*', ('(', ('10', '-', '20'), ')')))
```
and here's a screenshot: 
![image](https://user-images.githubusercontent.com/16870072/90125449-6046af00-dd62-11ea-93e4-00b44093b801.png)

Maybe there's a problem with the version you load from localhost?

**Comment by phorward** [comment]
OK I've recognized that this seems to be Tatsu v5.5.0 and not v4.4.0 as you used it, maybe its a bug in Tatsu that has been fixed?

**Comment by pressureless** [comment]
Hi @phorward ,
Thank you for your reply. At the beginning, I used Tatsu v5.5.0 and got the same error. Then I thought it might relate to the version since the [official](https://pypi.org/project/TatSu/) said |TatSu|>=5.0.0 requires Python>=3.8. So I changed Tatsu to v4.4.0, the error remained the same.

It's strange that the demo works correctly in the console in the [Pyodide REPL](https://pyodide-cdn2.iodide.io/v0.15.0/full/console.html). Is there a difference between the webpage version I used and the console version in the Pyodide REPL?

Here is the same error I got using Tatsu v5.5.0.
<img width="771" alt="image" src="https://user-images.githubusercontent.com/8511053/90141755-8c096b00-dd49-11ea-92ac-6dc6656be38f.png">
<img width="709" alt="image" src="https://user-images.githubusercontent.com/8511053/90141778-93307900-dd49-11ea-8b89-1d6632ddead3.png">

**Comment by rth** [comment]
@pressureless If are you are using Chrome could you try Firefox? The recursion limit is currently a set to a bit lower value there,
https://github.com/iodide-project/pyodide/blob/7398edb787aba8e229e00a81dbcadb519f5b0baf/src/pyodide.js#L273
with `sys.getrecursionlimit()` I get 315 in Chrome and 733 in Firefox (latest stable versions).

You could also try to increase the recursion limit manually with `sys.setrecursionlimit()` and see if that helps.

We should have Python 3.8 in the next release.

**Comment by pressureless** [comment]
Hi @rth ,
Thank you for your suggestion. I did use Chrome before. I've tried Firefox, the error remains. I've also increased the default limit to a bigger one(from 1000 to a very big number) at the beginning, it doesn't help.

Here is the msg from Firefox
<img width="560" alt="image" src="https://user-images.githubusercontent.com/8511053/90292405-d37a1f00-de4f-11ea-9cc2-f987b3d3410d.png">

**Comment by rth** [comment]
> It's strange that the demo works correctly in the console in the Pyodide REPL. Is there a difference between the webpage version I used and the console version in the Pyodide REPL?

Yes, then it's very strange. It should be exactly the same files as those that you download from the 0.15.0 release on Github. For instance you can check with `sys.version` that the compilation happened on `May 20 2020, 19:25:33` for both.

**Comment by ryanking13** [comment]
Hi @pressureless, this issue has been open for a very long time, and Pyodide has changed a lot since this issue was opened. Could you please try it again if you are still interested? I'll close this for now as resolved, and please open a new issue if you are still facing the error.
